# Generated by Django 2.2 on 2019-05-01 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auto_20190501_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_info',
            name='present_fees',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='emplo',
            name='emp_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
