# Generated by Django 2.2 on 2019-05-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_auto_20190501_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_masters',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.Company_Masters'),
        ),
    ]
