# Generated by Django 2.2 on 2019-05-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_auto_20190502_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_info',
            name='loc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.Location_Masters'),
        ),
        migrations.AlterField(
            model_name='comp_info',
            name='primary_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prim_emp', to='compliance.emplo'),
        ),
        migrations.AlterField(
            model_name='comp_info',
            name='sec_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secd_emp', to='compliance.emplo'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='loc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.Location_Masters'),
        ),
        migrations.AlterField(
            model_name='emplo',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.dept'),
        ),
    ]
