# Generated by Django 2.2 on 2019-05-02 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_auto_20190502_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_info',
            name='present_fees',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999999)]),
        ),
        migrations.AlterField(
            model_name='emplo',
            name='emp_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='location_masters',
            name='loc_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
