# Generated by Django 2.2 on 2019-07-01 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_auto_20190502_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('comp_name', models.CharField(max_length=100)),
                ('renewal', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=200)),
                ('law_authority', models.CharField(blank=True, max_length=250, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('date_expiry', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('present_fees', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999999)])),
                ('primary_emp', models.CharField(max_length=100)),
                ('sec_emp', models.CharField(max_length=100)),
                ('custody', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dept',
            name='loc_id',
        ),
        migrations.RemoveField(
            model_name='emplo',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='location_masters',
            name='comp_id',
        ),
        migrations.DeleteModel(
            name='Comp_Info',
        ),
        migrations.DeleteModel(
            name='Company_Masters',
        ),
        migrations.DeleteModel(
            name='dept',
        ),
        migrations.DeleteModel(
            name='emplo',
        ),
        migrations.DeleteModel(
            name='Location_Masters',
        ),
    ]
