# Generated by Django 2.2 on 2019-07-02 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_auto_20190701_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='compli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=8)),
                ('loc_name', models.CharField(max_length=100)),
                ('comp_name', models.CharField(max_length=100)),
                ('renewal', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=200)),
                ('law_authority', models.CharField(blank=True, max_length=250, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('date_expiry', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('present_fees', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999999)])),
                ('primary_emp', models.CharField(max_length=100)),
                ('sec_emp', models.CharField(max_length=100)),
                ('custody', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='compliance',
        ),
    ]
