# Generated by Django 2.2 on 2019-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_auto_20190705_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='date_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='date_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='renewal',
            field=models.DateField(blank=True, null=True, verbose_name='Renewal Date'),
        ),
    ]
