# Generated by Django 2.2 on 2019-07-04 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0012_auto_20190705_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compliance',
            new_name='compli',
        ),
    ]
