# Generated by Django 2.2 on 2019-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_auto_20190705_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compli',
            name='renewal',
            field=models.DateField(blank=True, null=True, verbose_name='Renewal Date YYYY-MM-DD'),
        ),
    ]
