# Generated by Django 2.2 on 2019-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_auto_20190705_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compli',
            name='renewal',
            field=models.DateField(blank=True, null=True, verbose_name='Renewal Date (YYYY-MM-DD)'),
        ),
    ]
